### ISSUE TITLE
Unable to use route.start()

### ISSUE THREAD

**Issue by sujeetbuddiga** [riot/route#116]
I'm using riot with webpack, I'm not able to understand how to use it

```
const home = require('./home.app.tag')
const riot = require('riot');
const route = require('riot-route')

riot.mount('home')
console.dir(route)
```

When I write to **route** to console I see a **default** object there, not sure how can I use and why is such a thing even present.

**There is the output:**
![op](https://user-images.githubusercontent.com/3041104/36412435-3e60b62e-1640-11e8-81a5-8f932412c9c2.png)

**Comment by sujeetbuddiga** [comment]
https://user-images.githubusercontent.com/3041104/36412356-e59b1db8-163f-11e8-86ba-27afd4ec8b3b.png

**Comment by laznic** [comment]
Assuming you're using Webpack 2, it automatically defaults to using the `module` entry in `package.json`, so it offers the ES2015 syntax version of `riot-route` where it's doing `export default route`, hence why you're seeing the `default` object. There are couple ways to work with this.

1. Use ES2015 `import` instead of `require`
2. Do `const route = require('riot-route').default` so you can directly access the `start`, `stop`, etc. functions with `route.start` etc.
3. Configure `resolve.mainFields` in your `webpack config` to point it to use `main` entry instead (this applies to all your `requires` / `imports`): https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by laznic** [comment]
@sujeetbuddiga I admit that me saying Webpack 2 is a bit misleading, but that's pretty much just meaning the newer version of Webpack. The very first Webpack version (< 2) worked a lot differently than the next release and has been pretty much the same since then. Therefore Webpack v3 could also be thought to be part of Webpack 2.

In any case, I'll update the previous comment so that it's not that misleading.

**Comment by sujeetbuddiga** [comment]
Thanks @laznic  for the quick response.
I will try and update the thread ASAP, but I"m unable to understand the importance of **default** object there.

Please share any references which you provide me to understand its importance.

**Comment by laznic** [comment]
This is just an issue with you using **CommonJS** import (`require(...)`) instead of **ES6**––imports/exports work a bit differently in these two.

In CommonJS, you'd export a module by using `module.exports = { ... }` and in ES6, the same thing is achieved by doing `export default ...`.  And this `export default` is actually a named import, except with the reserved name _default_,  hence it appears as the default object when you're using CommonJS import. 

Here is a StackOverflow conversation about the same thing: https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6

Hope this helps.

**Comment by GianlucaGuarini** [comment]
@laznic thanks for answering to this question. It's definitely not a route issue nor a webpack one. The solution is pretty simple and there tons of tutorial or discussions about this topics. There is no need to track this issue here since it's related to the compilation tools used to generate the js bundle. Thanks for asking it anyway.

p.s.
our [webpack example](https://github.com/riot/examples/tree/gh-pages/webpack) is a good place where to start

**Comment by sujeetbuddiga** [comment]
thanks @laznic  for helping me out.
@GianlucaGuarini  i wasn't aware of that, hope you understand that.
