### ISSUE TITLE
Add Middleware to Routes

### ISSUE THREAD

**Issue by kazzkiq** [riot/route#40]
It would be interesting to have the option of middlewares on routes, executing before they get properly handled. E.g.

``` js
riot.route('/products/new', function() {
    // show view
}, ['UserController.isLogged']);
```

The idea is that middleware would always return a boolean. `true` firing the route callback, `false` preventing it from being handled.

There is also the `.next()` approach, discussed on Issue #25. Maybe we could define which approach would be the more interesting.

**Comment by Ldiab** [comment]
As I come from Node/Express, I see the next() approach more natural, because you are really processing some data and then controlling the flow because of the results. For middleware I see is the best options, because you just need to insert at the top, and then after them you insert your routes. With your approach I just see it as a Flag, which yeah, it makes sense, but you are losing the posibility to modify the data of the "request" which can be very useful for users panels and permissions. It's not natural (for me), because you are really hitting that path is just you don't have the permissions or you are just going to a deeper level.

Just my opinion here :P

**Comment by kazzkiq** [comment]
Just took a look at Express middleware documentation and the `next()` approach seems more logical.

So just to get things straight, using this approach I'm only obligated to use `next()` when adding middlewares, otherwise I could simply omit its parameter from the callback and let it fire automatically? e.g.

```js

// Using Middleware
riot.route('product/add', function(collection, id, action, next) {
    // do some stuff
    next();
});

// Regular route
riot.route('product/add', function(collection, id, action) {
    // do some stuff that fires automatically
});

```

**Comment by Ldiab** [comment]
Mmmm I don't understand the user login case, I mean, with this approach you just need to do something like this:
```
var userIsLogged = false;
riot.route('/', function(next){
	checkWithServerIfUserIsLogged().then(function(isLogged){
		userIsLogged = isLogged;
		next();
	});
});

riot.route('/userpanel', function(next){
	if (userIsLogged){
		next();
	}else{
		redirectToOtherSite();
	}
});

riot.route('/userpanel/changepass', function(next){
	// Here you will be logged yes or yes, because you have checked it in a supperior path
});
```
The only thing I would ask is for something to check if the user is actually hitting the path is being routed, some this.isTargetPath or something like this. so you could do something like this:
```
var userIsLogged = false;
riot.route('/', function(next){
	var self = this;
	checkWithServerIfUserIsLogged().then(function(isLogged){
		userIsLogged = isLogged;
		if (self.isTargetPath){
			setView('Homepage');
		}else{
			next();
		}
	});
});
```

I think this is the most powerful way to manage routes... What do you think?

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
