### ISSUE TITLE
Routing without hash !

### ISSUE THREAD

**Issue by didierfranc** [riot/route#53]
Hi guys (@cognitom @GianlucaGuarini ), is it possible to have routes without hash ?

I tried this :

```
riot.route.base('/')
```

It's working for `/first` but it can't get the second one in `/first/second` and I get this error : 

![capture d ecran 2016-02-10 a 00 47 04](https://cloud.githubusercontent.com/assets/14132464/12934568/d308bb68-cf8f-11e5-89cb-30de5be63a5e.jpg)

I get the same error with just adding trailing slash like that `/first/`  

It's the way used here https://github.com/riot/examples/blob/gh-pages/router-complex/index.html#L28 but it seems not working.
### As I said on Gitter :

In fact the **riot.route.base** can’t be the same as parser

`#/first/second`  is working
`/first#second`  is working
`/first/second` is not working

Obviously, this bug appears only when we enter the adress directly in the adress bar. I get almost the same bug with every version of **superstatic**.

**Comment by didierfranc** [comment]
Am I the only one thinking riot router is partially broken ?

**Comment by cognitom** [comment]
@didierfranc you're right. We should fix this. Thanks for reporting.

**Comment by atflick** [comment]
@cognitom @GianlucaGuarini have there been any fixes for this?  I am also trying to set a base route to '/' and not having any success with everything I have tried.  Thanks!

**Comment by slai** [comment]
If you're getting the error in the console as shown in the first post, this is probably because you have included `riot+compiler.js` like so -

```html
<script src="riot+compiler.min.js"></script>
```

This works for `/` and `/first` URLs, but when you add another level, e.g. `/first/second`, your browser will then attempt to resolve `riot+compiler.min.js` within the new base, i.e. `/first/riot+compiler.min.js`. That probably doesn't exist, so for all not found requests, your server is responding with your HTML page (as it should). Unfortunately, your browser is expecting JS, hence the `unexpected token` error. 

Try going to the network tab and seeing what comes back for the JS request as well as the URL it sent.

The fix is to root your script src attribute, i.e. 

```html
<script src="/riot+compiler.min.js"></script>
```

I'm just written something with this scenario and it works using 3.1.1.

**Comment by bminer** [comment]
This can probably be closed, right?

**Comment by GianlucaGuarini** [comment]
@bminer you are right thanks for the reminder
