### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by jonaspm** [riot/route#86]
Hi! I am having trouble with nested routes... the problem is as follows:
1. Open app (http://localhost:3000#)
2. Go to (http://localhost:3000#app)
3. Content is blank (nav-bar does show)
4. After adding '/' at the end of URL from step2 and hitting Enter, content shows.

My app structure is as follows:

```
<app>
	<router>
		<route path="">
			<app-page-login></app-page-login>
		</route>
		<route path="register">
			<app-page-register></app-page-register>
		</route>
		<route path="app">
			<main-app></main-app>
		</route>
	</router>
</app>

<main-app>
	<app-nav></app-nav>
	<div class="container" data-is="{ currentPage }"></div>
	<script>
		var self = this
		, r = route.create()
		r('app', dashboard)
		r(notfound)

		function dashboard() {
		  self.update({currentPage: 'app-page-dashboard'})
		}

		function notfound() {
			self.update({currentPage: 'page-404'})
		}

		this.on('route', (page) => {
			if (typeof page === undefined)
				dashboard()
			console.log(page)
		})
	</script>
</main-app>
```

Note that this.on('route', (page) => ... is an unsuccessful try to fix the problem.

**Comment by cognitom** [comment]
@jonaspm sorry for my late reply, could you make a example on [Plunker](http://riotjs.com/examples/plunker/?app=bug-reporter)?

**Comment by jonaspm** [comment]
@cognitom here it is:
http://plnkr.co/edit/qFpVM4?p=preview

Try navigating through routes several times... in one point on time the router stops working and error console log is shown...

**Comment by exp10r3r** [comment]
This has become an issue for our use case as well.
We have a similar setup, wherein tags represent pages which have been grouped into modules and they are to have their own routing.

Starting up the app, it works perfectly whilst you are clicking around or using the browser navigation buttons, but as soon as the browser refresh button is pressed whilst you are in a tag which has declared its own `const router = riot.route.create()`, the paths configured in this `router` don't work, until this page is navigated back using browser actions like back,forward or click.

I debugged this issue further and found that router callbacks don't get invoked unless the internal `emit` function is called. And when nested routers are defined, `emit` is not called at all for the nested router.
This is probably by design, since calling `emit` will trigger other routers as well that were either previously declared or were defined in the parent tag, which would again cause issues.
I'm assuming that is how `emit` works. I know I'm probably wrong.

**Comment by jonaspm** [comment]
@cognitom Could you reproduce the issue?

**Comment by agersant** [comment]
I have a similar issue in the app I work on. Here is a minimal [plunker reproducing the issue](http://plnkr.co/edit/PoEhZvrVviRgPkRV0kRU?p=preview).

Steps to repro after opening the plunker:

1. Click subrouter
2. Click basic
3. Observe console output `TypeError: r is undefined`

The site of the error is:
```
riot.tag2('router', '<yield></yield>', '', '', function(opts) {
    var this$1 = this;


    this.route = route$1.create();
    this.select = function (target) {
      [].concat(this$1.tags.route)
        .forEach(function (r) { return r.show = (r === target); });
    };

    this.on('mount', function () {

      window.setTimeout(function () { return route$1.start(true); }, 0);
    });
});
```

From my modest understanding of Riot's internal, I would guess that the issue is the subroute created by the <router> tag isn't stopped when said router tag is unmounted. I'll submit a PR with a proposed fix.
